# Generated by Django 4.2.6 on 2023-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_objecttoremigrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
