# Generated by Django 4.2.6 on 2023-10-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_osoba_data_dodania_alter_osoba_plec_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
