# Generated by Django 4.2.6 on 2023-11-13 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0008_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='wlasciciel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Osoba', to=settings.AUTH_USER_MODEL),
        ),
    ]
